In [1]:
import numpy as np

arr = np.arange(0,20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [2]:
arr_2d = arr.reshape(4,5)
print(arr_2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [3]:
arr_3d = np.random.randint(1,10, size= (3,3))
print(arr_3d)

[[3 8 2]
 [2 5 4]
 [2 7 5]]


In [7]:
trans = arr_3d.transpose()
print(trans)

[[3 2 2]
 [8 5 7]
 [2 4 5]]
