In [1]:
import numpy as np

In [8]:
arr1 = np.random.randint(1,10,size=(4,2))
arr2 = np.random.randint(1,10,size=(2,3))
print("Matrix 1")
print(arr1)
print("Matrix 2")
print(arr2)

Matrix 1
[[3 1]
 [3 2]
 [5 6]
 [9 2]]
Matrix 2
[[6 6 2]
 [5 6 1]]


In [9]:
matmul = np.matmul(arr1,arr2)
print(matmul)

[[23 24  7]
 [28 30  8]
 [60 66 16]
 [64 66 20]]


In [10]:
transpose = matmul.T
print(transpose)

[[23 28 60 64]
 [24 30 66 66]
 [ 7  8 16 20]]
