In [1]:
import numpy as np

In [2]:
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
print("3rd element : ",arr1[2])
print("Last element : ",arr1[-1])

3rd element :  2
Last element :  9


In [7]:
print("First 5 elements : ",arr1[:5])
print("Every other element : ",arr1[::2])
print("Array reversed : ",arr1[::-1])

First 5 elements :  [0 1 2 3 4]
Every other element :  [0 2 4 6 8]
Array reversed :  [9 8 7 6 5 4 3 2 1 0]


In [28]:
array_2D = np.array([[1,2,3],[4,5,6]])
print(array_2D)

[[1 2 3]
 [4 5 6]]


In [14]:
print("Entire 1st row:", array_2D[0,:])

Entire 1st row: [1 2 3]


In [22]:
subarray = array_2D[:2, -2:]

In [23]:
subarray = array_2D[:2, -2:]

In [24]:
subarray = array_2D[:2,-2:]
print("subarray :\n", subarray)

subarray :
 [[2 3]
 [5 6]]


In [31]:
sliced_array= array_2D[1::2, ::2]
print("Every other element in 2D Array:\n", sliced_array)

Every other element in 2D Array:
 [[4 6]]


In [30]:
array_3D = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(array_3D)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [33]:
array_3D = np.random.randint(1,21,(2,3,4))
print(array_3D)


[[[ 9  9 13  8]
  [18 11 18 17]
  [12  2 20 12]]

 [[15 20 19 20]
  [11  5 13  1]
  [14  5  6 14]]]
