In [1]:
import numpy as np

In [3]:
arr2 = np.random.randint(50,100,size=(5,5))
print(arr2)

[[95 53 96 60 94]
 [70 50 99 95 98]
 [99 95 82 79 61]
 [82 78 95 63 67]
 [73 59 51 96 62]]


In [4]:
new_arr = arr2[1:4, 1:4]
print(new_arr)

[[50 99 95]
 [95 82 79]
 [78 95 63]]


In [6]:
arr2[1:4, 1:4] = 0
print(arr2)

[[95 53 96 60 94]
 [70  0  0  0 98]
 [99  0  0  0 61]
 [82  0  0  0 67]
 [73 59 51 96 62]]
