In [29]:
import numpy as np

In [32]:
arr2 = np.random.randint(10,100,size=(5,3))
print(arr2)

[[93 74 40]
 [61 33 45]
 [38 47 43]
 [55 75 34]
 [19 25 50]]


In [35]:
transpose = arr2.T
print(transpose)

[[93 61 38 55 19]
 [74 33 47 75 25]
 [40 45 43 34 50]]


In [ ]:
print("Mean of original array :",np.mean(arr2))
print("Mean of Transpose :",np.mean(transpose))