In [2]:
import numpy as np
array_1d = np.array([1,2,3])

In [3]:
print(array_1d)

[1 2 3]


In [5]:
array_2D = np.array([[1,2],[3,4]])

In [6]:
print(array_2D)

[[1 2]
 [3 4]]


In [7]:
array_3D = np.array ([[[1,2], [3,4],[5,6]]])

In [8]:
print(array_3D)

[[[1 2]
  [3 4]
  [5 6]]]


In [9]:
zeros = np.zeros((2,3))

In [10]:
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
ones = np.ones((3,4))

In [12]:
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
full_array = np.full((2,2),7)
print(full_array)

[[7 7]
 [7 7]]


In [15]:
range_array = np.arange(0,10)
print(range_array)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
step_array = np.arange(0,10,2)
print(step_array)

[0 2 4 6 8]


In [17]:
linespace = np.linspace(0,1,10)
print(linespace)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [18]:
random_array = np.random.rand(3,3)
print(random_array)

[[0.32500942 0.36972559 0.66567169]
 [0.02508686 0.85713759 0.43339434]
 [0.23736336 0.24756013 0.67063424]]


In [20]:
random_int_array = np.random.randint(1,10,size = (2,2))
print(random_int_array)

[[7 2]
 [3 7]]


In [22]:
id = np.eye(4)
print(id)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
dig = np.diag([1,2,3])
print(dig)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [27]:
emp_1d = np.empty(5)
print(emp_1d)

[2.12199579e-314 6.36598737e-314 1.06099790e-313 1.48539705e-313
 1.90979621e-313]


In [28]:
emp_2d = np.empty((2,3))
print(emp_2d)

[[0. 0. 0.]
 [0. 0. 0.]]
