In [1]:
import numpy as np

In [14]:
l1 = np.array([1,2,3,4,5])
l2 = np.array([6,7,8,9,10])
l3 = np.array([11,12,13,14,15])
l4 = np.array([16,17,18,19,20])

In [16]:
arr1 = np.concatenate((l1,l2))
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr2 = np.concatenate((l3,l4))
arr2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [18]:
np.sum(arr1)

55

In [32]:
print("Addition")
for i in range(len(arr1)):
    sum = arr1[i] + arr2[i]
    print(sum)

np.add(arr1,arr2)

Addition
12
14
16
18
20
22
24
26
28
30


array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [33]:
print("Subtraction")
for i in range(len(arr1)):
    sub = arr1[i] - arr2[i]
    print(sub)

np.subtract(arr1,arr2)

Subtraction
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10


array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [36]:
print("Multilpication")
for i in range(len(arr1)):
    mul = arr1[i] * arr2[i]
    print(mul)


np.multiply(arr1,arr2)

Multilpication
11
24
39
56
75
96
119
144
171
200


array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [38]:
print("Division")
for i in range(len(arr1)):
    div = arr1[i] / arr2[i]
    print(div)
         
np.divide(arr1,arr2)

Division
0.09090909090909091
0.16666666666666666
0.23076923076923078
0.2857142857142857
0.3333333333333333
0.375
0.4117647058823529
0.4444444444444444
0.47368421052631576
0.5


array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ])

In [39]:
np.exp(arr1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])